site_name: Tech Blog
#docs_dir: docs/
site_url: https://morai-techblog.github.io/

repo_url: https://github.com/morai-techblog/morai-techblog.github.io
edit_uri: blob/main/docs/


theme:
  name: material
  # custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate  
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - Home: index.md


