EJ:
  name: Eunjung Kim
  description: Technical Writer | <br> 모라이의 언어와 글을 담당합니다.
  avatar: "https://ca.slack-edge.com/T01APHTC397-U04CMQ44CRG-4c8894d7da3c-512"
  id: _2

Hojun:
  name: Hojun Lim
  description: Virtual Data Engineer | <br> 모라이의 데이터셋과 센서 모듈을 개발합니다.
  avatar: "https://ca.slack-edge.com/T01APHTC397-U02NUKF9B4Y-b0a38c7a3fa5-512"
  id: _1
