name: Check korean grammar on pull request comment

on:
  [pull_request]
  
jobs:
  grammar_check:
    runs-on: ubuntu-latest
    steps:
    - name: "맞춤법 검사"
      uses: jckdotim/korean-grammar-action@v0.2.6
      # uses: heumsi/korean-grammar-action@v0.2.8
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
